#!/usr/bin/env python3
"""Transcribe the curriculum and a produced schedule into a Pol instance.

This is a TRANSCRIBER, not a checker, and the distinction is the whole basis of
trusting the audit. It decides exactly one thing:

    b-nth — which hour of that subject a lesson is, by position in week order.

Everything else is a literal copy: a room is a room, a booking is a booking.
And even that one decision is checked rather than trusted — `hours-not-doubled`
in timetable.claims fails if two lessons are given the same ordinal, and
`curriculum-delivered` / `nothing-extra` between them force the numbering to be
a bijection onto the programme. A transcriber that miscounted would be caught
by the file it is feeding.

    ./to_pol.py schedule.json -o build/timetable.pol
"""
import argparse
import json
import os
import sys

import yaml

# Members of the enumerated types the library declares: an entity may not
# redeclare them (§7 — names are global across the loaded universe).
RESERVED = {"plain", "computers", "gym", "vacant",
            "school", "slot", "room", "teacher", "subject", "group", "demand",
            "booking", "ordinal", "qualification", "blackout", "facility",
            "size-t", "day-t", "period-t", "id-t"}


class Names:
    """Every entity name emitted, checked for the collisions Pol forbids."""

    def __init__(self):
        self.seen = set()

    def fresh(self, base):
        if base in RESERVED:
            sys.exit(f"'{base}' is a reserved name in timetable.lib.pol — "
                     f"rename it in curriculum.yaml")
        name, n = base, 1
        while name in self.seen:                 # a tampered file may repeat one
            n += 1
            name = f"{base}-again{n}"
        self.seen.add(name)
        return name


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("schedule")
    ap.add_argument("--curriculum", default="curriculum.yaml")
    ap.add_argument("-o", "--out", default="timetable.pol")
    ap.add_argument("--lib", default="timetable.lib.pol")
    args = ap.parse_args()

    cur = yaml.safe_load(open(args.curriculum))
    sched = json.load(open(args.schedule))
    N = Names()

    days, periods = cur["week"]["days"], cur["week"]["periods"]
    slots = [f"{d}-{p}" for d in days for p in periods]
    order = {s: i for i, s in enumerate(slots)}

    # ── the capacity ladder: distinct seat counts, smallest first ────────────
    sizes = sorted({r["seats"] for r in cur["rooms"].values()} |
                   {g["size"] for g in cur["groups"].values()})
    if len(sizes) > 4:
        sys.exit(f"{len(sizes)} distinct capacities, but `fits` in "
                 f"timetable.lib.pol walks a ladder of 4 — extend the form "
                 f"(one disjunct per class) or bucket the capacities")
    size_of = {n: f"seats-{n}" for n in sizes}

    def klass(n):
        """The smallest class that seats n — a group's own size class."""
        return size_of[min(s for s in sizes if s >= n)]

    L = []
    add = L.append
    add(f'; GENERATED by to_pol.py from {os.path.basename(args.curriculum)} and '
        f'{os.path.basename(args.schedule)} — do not edit.')
    add(f'; The schedule was produced by: {sched.get("produced_by", "?")} '
        f'({sched.get("mode", "?")}).')
    add(f'(load "{args.lib}")')
    add("")
    add("(instance week school")
    add("  ; ── the week ──")
    add(f"  (day-t {' '.join(days)})")
    add(f"  (period-t {' '.join(periods)})")
    for i, s in enumerate(slots):
        nxt = slots[i + 1] if i + 1 < len(slots) else "vacant"
        d, p = s.rsplit("-", 1)
        add(f"  (slot {N.fresh(s)} (next {nxt}) (day {d}) (period {p}))")

    add("  ; ── capacity, as a small named scale ──")
    for i, n in enumerate(sizes):
        nxt = size_of[sizes[i + 1]] if i + 1 < len(sizes) else "vacant"
        add(f"  (size-t {N.fresh(size_of[n])} (bigger {nxt}))")

    add("  ; ── the estate ──")
    for r, spec in cur["rooms"].items():
        add(f"  (room {N.fresh(r)} (provides {spec['facility']}) "
            f"(holds {size_of[spec['seats']]}))")

    add("  ; ── staff, syllabus, groups ──")
    for t in cur["teachers"]:
        add(f"  (teacher {N.fresh(t)})")
    for s, spec in cur["subjects"].items():
        add(f"  (subject {N.fresh(s)} (needs {spec['needs']}))")
    for g, spec in cur["groups"].items():
        add(f"  (group {N.fresh(g)} (size {klass(spec['size'])}))")

    add("  ; ── who may teach what, and who is not available when ──")
    for t, spec in cur["teachers"].items():
        for s in spec["teaches"]:
            add(f"  (qualification {N.fresh(f'may-{t}-{s}')} "
                f"(q-teacher {t}) (q-subj {s}))")
    for t, spec in cur["teachers"].items():
        for u in spec.get("unavailable", []):
            add(f"  (blackout {N.fresh(f'not-{t}-{u}')} "
                f"(x-teacher {t}) (x-slot {u}))")

    add("  ; ── counting without numbers: one ordinal per possible hour ──")
    top = max(h for prog in cur["programme"].values() for h in prog.values())
    top = max(top, max((sum(1 for b in sched["lessons"]
                            if b["group"] == g and b["subject"] == s)
                        for g in cur["groups"] for s in cur["subjects"]), default=0))
    ordinal = {k: f"hour-{k}" for k in range(1, top + 1)}
    add(f"  (ordinal {' '.join(ordinal[k] for k in range(1, top + 1))})")

    add("  ; ── THE CURRICULUM: one entity per hour the programme demands ──")
    for g, prog in cur["programme"].items():
        for s, hours in prog.items():
            for k in range(1, hours + 1):
                add(f"  (demand {N.fresh(f'owed-{g}-{s}-{k}')} "
                    f"(d-group {g}) (d-subj {s}) (d-nth {ordinal[k]}))")

    add("  ; ── THE TIMETABLE: one entity per lesson the solver placed ──")
    # The only decision in this file: rank each lesson within its group's run
    # of that subject, in week order.
    lessons = sorted(sched["lessons"],
                     key=lambda b: (b["group"], b["subject"],
                                    order.get(f"{b['day']}-{b['period']}", 99)))
    nth, ids, rows = {}, [], []
    for b in lessons:
        key = (b["group"], b["subject"])
        nth[key] = nth.get(key, 0) + 1
        if nth[key] > top:
            sys.exit(f"{b['group']} has more hours of {b['subject']} than any "
                     f"ordinal names — the schedule over-delivers beyond the scale")
        at = f"{b['day']}-{b['period']}"
        name = N.fresh(f"{b['group']}-{b['subject']}-{at}")
        ids.append(N.fresh(f"id-{name}"))
        rows.append(f"  (booking {name} (b-group {b['group']}) (b-subj {b['subject']}) "
                    f"(b-teacher {b['teacher']}) (b-room {b['room']}) (b-slot {at}) "
                    f"(b-nth {ordinal[nth[key]]}) (b-id {ids[-1]}))")
    add(f"  (id-t {' '.join(ids)})")
    L.extend(rows)
    add("  )")
    add("")
    add("(use school)")
    add("(initial week)")
    add("")
    add("; Where the curriculum runs out — declared in the library, invoked here")
    add("; because a loaded file may not carry a transition of its own.")
    add("(silence-windows a b c)")
    add("(silence-doubling a b)")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"transcribed {len(lessons)} lessons and "
          f"{sum(sum(p.values()) for p in cur['programme'].values())} demanded hours "
          f"-> {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
